apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-ingress-nginx
  namespace: kube-system
spec:
  valuesContent: |
    controller:
      watchIngressWithoutClass: true
      publishService:
        enabled: true
      hostNetwork: false
      dnsPolicy: ClusterFirst
      hostPort:
        enabled: false
      kind: Deployment
      replicaCount: 2
      service:
        enabled: true
        type: LoadBalancer
      ingressClassResource:
        name: nginx-internal
        controllerValue: "k8s.io/ingress-nginx-internal"
        default: true
