apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: ingress-ippool
  namespace: metallb-system
spec:
  addresses:
    - 10.156.233.146/32
  serviceAllocation:
    priority: 100
    serviceSelectors:
      - matchExpressions:
          - key: app.kubernetes.io/name
            operator: In
            values:
              - rke2-ingress-nginx
